version: '3.1'

services: # creating 2 services for docker-compose
  # service 1: creating actual db with binding port:27017 to system & setting up 'name & password' for db
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017 #
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  # service 2: UI for mongo db which is binding port:8081 to system (later we can do localhost:8081 to access UI to show db entries)
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/ # connection string to db (username, password, service name & port)
